# Generated by Django 3.1.4 on 2020-12-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('date_published', models.DateTimeField()),
                ('thumbnail_url', models.TextField(null=True)),
                ('video_id', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ('date_published',),
            },
        ),
    ]
