# Generated by Django 3.1.4 on 2020-12-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('latest_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='LatestDateTime',
        ),
    ]
