# Generated by Django 3.1.4 on 2020-12-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search', '0002_auto_20201211_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='LatestTime',
        ),
    ]
