# Generated by Django 3.1.4 on 2020-12-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search', '0003_auto_20201211_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablestorage',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
